#!/bin/bash

echo "Making Agent"
cd agent
make clean > /dev/null 2>&1 
make html > /dev/null 2>&1
echo "Done."

echo "Syncing Agent Files"
s3cmd sync --delete-removed -P --exclude '*DS_Store' --exclude *buildinfo* agent/_build/html/ s3://es-agent
echo "Done."
s3cmd sync -P --exclude '*DS_Store' --exclude *buildinfo* agent/_build/html/ s3://es-agent
